### ISSUE TITLE
PROHIBIDO

### ISSUE THREAD

**Issue by gaal1le0** [DanBaDo/React---SecondsCounter#1]
https://github.com/DanBaDo/React---SecondsCounter/blob/28759bd6794e8f3876ac5ea9ee459032fda57b60/src/js/index.js#L23

Está prohibido el uso de `Class`, esto va a ser deprecado en breves en React por un tema de gestión de memoria que puedo contarte si tienes curiosidad.
Debes rehacer esa parte sin utilizar class y crear el componente necesario para resolver tu problema. Además recuerda que el archivo `index.js` es el punto de entrada de tu aplicación y por ende no puede estar tan cargado de cosas, refactoriza un poco.

PD: Cuando hayas acabado no olvides de cerrar el ISSUE y reenviar la tarea a través de BreathCode.

**Comment by DanBaDo** [comment]
Debes de tener en el correo la invitación para el repo para revisar el pull request.
He eliminado la clase. Los componentes ya estaban divididos.
Creo que ha habido un error, porque la Class no la estaba empleando para crear el componente. Sólo la empleaba para la lógica del conteo y la conversión del contador a strings, sancando partido de los getters para que incrementase el contador de forma automática. De todos modos, ya está eliminado.

**Comment by gaal1le0** [comment]
Si, he visto que usabas las clases para aprovechar esa funcionalidad del getter y el setter, pero eso no quiero que lo mezcles con las funciones flechas, produce mucha confusión, aunque no sea para crear un componente 😄

**Comment by DanBaDo** [comment]
Entregado en BreathCode
